### ISSUE TITLE
Improve error messages to include line number of MusicXML file

### ISSUE THREAD

**Issue by mogenslundholm** [w3c/mnxconverter#3]
I am with absolutely no knowledge of Python.

I would be a big advantage for me if an error had _file name_ and _line number_ for the MusicXML file included in the error message. It is hard for me to find the file corresponding to an error and where in this file is the error?
(While the error position in the Python file is very precise. Is it possible?)

It is not impossible to hunt the error - found this (ValueError: Invalid duration fraction 3/2):

    C:\Users\Mogens Lundholm\Desktop\MNX-test\MusicXml>python convert.py 12.musicxml
    Traceback (most recent call last):
      File "convert.py", line 8, in <module>
        print(put_mnx_common_score(s).decode('utf8'))
      File "C:\Users\Mogens Lundholm\Desktop\MNX-test\MusicXml\mnxconverter\mnx_common.py", line 38, in put_score
        return writer.get_filedata()
      File "C:\Users\Mogens Lundholm\Desktop\MNX-test\MusicXml\mnxconverter\mnx_common.py", line 56, in get_filedata
        self.write_parts()
      File "C:\Users\Mogens Lundholm\Desktop\MNX-test\MusicXml\mnxconverter\mnx_common.py", line 115, in write_parts
        self.write_part(part)
      File "C:\Users\Mogens Lundholm\Desktop\MNX-test\MusicXml\mnxconverter\mnx_common.py", line 122, in write_part
        self.write_bar_part(part_el, bar, bar.bar_parts[part.part_id])
      File "C:\Users\Mogens Lundholm\Desktop\MNX-test\MusicXml\mnxconverter\mnx_common.py", line 128, in write_bar_part
        self.write_sequence(measure_el, sequence)
      File "C:\Users\Mogens Lundholm\Desktop\MNX-test\MusicXml\mnxconverter\mnx_common.py", line 145, in write_sequence
        self.write_sequence_items(sequence_el, sequence.items)
      File "C:\Users\Mogens Lundholm\Desktop\MNX-test\MusicXml\mnxconverter\mnx_common.py", line 150, in write_sequence_items
        self.write_event(parent_el, item)
      File "C:\Users\Mogens Lundholm\Desktop\MNX-test\MusicXml\mnxconverter\mnx_common.py", line 160, in write_event
        event_el.attrib['value'] = microformat_duration(event.duration)
      File "C:\Users\Mogens Lundholm\Desktop\MNX-test\MusicXml\mnxconverter\mnx_common.py", line 241, in microformat_duration
        raise ValueError(f'Invalid duration fraction {frac}')
    ValueError: Invalid duration fraction 3/2
 
I have attached the file 12.musicxml

[12.zip](https://github.com/w3c/mnxconverter/files/5160778/12.zip)
 
PS: Suspect this to happen when the measure is not 4/4 and a pause is a whole measure.

**Comment by adrianholovaty** [comment]
@mogenslundholm Thanks for the suggestion — I agree this is worth doing, as long as it's not too cumbersome in the converter code. Will investigate.

**Comment by adrianholovaty** [comment]
This is now done, as of ffe07d98b.
